### ISSUE TITLE
Is this an active project?

### ISSUE THREAD

**Issue by fabiocaccamo** [BertrandBordage/django-tree#1]

**Comment by BertrandBordage** [comment]
This question can be split in three parts:
- Is the project abandoned?
- Is version 1.0 planed? (The first stable version that will include SQLite & MySQL support)
- When will there be further work on this project?

Here are the answers:
- No, the project is not abandoned. I am still as motivated to finish it as the day I started it.
- I plan on making a stable version containing SQLite & MySQL support, as well as lots of additional features such as a drag & drop tree widget (better than jqTree & jsTree) and an admin integration of it. I even already have a working version of the widget, its code just needs to be refactored a bit.
- Unfortunately, I couldn’t find yet a financial support to finish building this project. I wrote a project of crowdfunding campaign, it even contains the replacement of django-treebeard by django-tree in Wagtail & django CMS. I just need to convince more people before launching that crowdfunding campaign. If you’re willing to help it become a reality, tell about this project and help me convince people to do it ^^ That way, we’ll no longer have broken tree structures in Django…

**Comment by victorct-pulsarup** [comment]
What about today?

**Comment by BertrandBordage** [comment]
The status didn’t really improve. I use django-tree in one project, but I don’t have enough time to work on this. Also, I quite lack the motivation now. I’ve been working on a ton of other projects since, and I never faced a situation yet where using django-treebeard was really more annoying than it would be annoying to port django-tree to MySQL & SQLite.

So for now it’s the *status quo*. I will keep updating django-tree for the project I created that uses it. But it will likely never have stable release & documentation. I know that’s a waste, given all the time I spent on it and the quality of the test suite I created. But it’s not a rational argument in favour of putting a lot of effort into this.

If some high-skilled SQL developer has the motivation to finish this, I’m totally open to gradually handing her/him over the project :)

**Comment by fabiocaccamo** [comment]
@victorct-pulsarup some time ago I was in your same situation till I decided to write [`django-treenode`](https://github.com/fabiocaccamo/django-treenode).

**Comment by stuaxo** [comment]
Is it worth documenting the work needed to port to MySQL or even Sqlite somewhere ?

You never know, someone might pick it up (may even be worth seeking funding for same).

**Comment by BertrandBordage** [comment]
@stuaxo I’m not sure there’s a lot to describe. To have MySQL or SQLite support, ideally an SQL trigger has to be implemented to batch update the paths in the same transaction, or worst case scenario put the logic in a Django signal.
