### ISSUE TITLE
In beta, it can’t be used yet in production.

### ISSUE THREAD

**Issue by figure002** [BertrandBordage/django-tree#12]
I saw this notice in the README and wondered why it's not production ready. Is it because only PostgreSQL is supported, or are there other reasons?

And also in the README:

> Django-tree requires Django 1.8, 1.11 or 2.0

But I see `Django>=3.2,<3.3` in requirements.txt. So I'm guessing the README needs to be updated as well. Has this been tested with the current version of Django?

**Comment by BertrandBordage** [comment]
This mention is here to not get expectations too high. Although I made the code itself as good as possible, I don't have enough time to keep the package itself great. That's why there is no continuous integration, why the documentation is basic and can be outdated, as you noticed.

I might allocate some time in 2024 to a member of my team to fix those issues, but I cannot guarantee it yet.

**Comment by figure002** [comment]
Alright, I understand. Thanks for the quick reply!
